# Generated by Django 5.0.1 on 2026-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
