# Generated by Django 5.0.1 on 2025-12-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_ai_interaction_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiinteractionlog',
            new_name='admin_ai_in_endpoin_146724_idx',
            old_name='admin_ai_in_endpoin_idx',
        ),
    ]
