# Generated by Django 5.0.1 on 2025-12-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_conversation_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='admin_ai_co_user_id_e1182d_idx',
            old_name='admin_ai_co_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmessage',
            new_name='admin_ai_co_convers_336b34_idx',
            old_name='admin_ai_co_convers_idx',
        ),
    ]
