# Generated by Django 5.0.1 on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_widget_enabled',
            field=models.BooleanField(default=False, help_text='Enable the AI widget and conversations feature'),
        ),
    ]
