# Generated by Django 5.0.1 on 2025-12-05 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('source', models.CharField(choices=[('ukri', 'UKRI'), ('nihr', 'NIHR'), ('catapult', 'Catapult')], db_index=True, max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('funding_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('hash_checksum', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grants',
                'indexes': [models.Index(fields=['slug'], name='grants_slug_82dbc0_idx'), models.Index(fields=['hash_checksum'], name='grants_hash_ch_aac60e_idx'), models.Index(fields=['source', 'deadline'], name='grants_source_c1433e_idx')],
                'unique_together': {('slug', 'source')},
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ukri', 'UKRI'), ('nihr', 'NIHR'), ('catapult', 'Catapult')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='running', max_length=50)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('grants_created', models.IntegerField(default=0)),
                ('grants_updated', models.IntegerField(default=0)),
                ('grants_skipped', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scrape_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source'], name='scrape_logs_source_0dd895_idx'), models.Index(fields=['status'], name='scrape_logs_status_6f320f_idx'), models.Index(fields=['started_at'], name='scrape_logs_started_8c85ca_idx')],
            },
        ),
    ]
