# Generated by Django 5.0.1 on 2025-12-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_add_grants_found_to_scrapelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='source',
            field=models.CharField(choices=[('ukri', 'UKRI'), ('nihr', 'NIHR'), ('catapult', 'Catapult'), ('innovate_uk', 'Innovate UK')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='source',
            field=models.CharField(choices=[('ukri', 'UKRI'), ('nihr', 'NIHR'), ('catapult', 'Catapult'), ('innovate_uk', 'Innovate UK')], db_index=True, max_length=50),
        ),
    ]
