# Generated by Django 5.0.1 on 2025-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_alter_grant_source_alter_scrapelog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='eligibility_checklist',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]

