# Generated by Django 5.0.1 on 2026-01-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_add_exclusions_checklist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eligibilityquestionnaire',
            new_name='eligibility_user_id_3395c2_idx',
            old_name='eligibility_user_created_idx',
        ),
        migrations.AddField(
            model_name='grant',
            name='opening_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
