# Generated by Django 5.0.1 on 2026-01-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_add_opening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=50),
        ),
    ]
