# Generated by Django 5.0.1 on 2026-01-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0010_add_cancelled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_findings', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('deleted_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scrape_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_report', to='grants.scrapelog')),
            ],
            options={
                'db_table': 'scrape_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('new', 'New Grant'), ('updated', 'Updated Grant'), ('deleted', 'Deleted/Unavailable Grant'), ('error', 'Error Processing Grant')], db_index=True, max_length=20)),
                ('grant_slug', models.SlugField(max_length=500)),
                ('grant_source', models.CharField(choices=[('ukri', 'UKRI'), ('nihr', 'NIHR'), ('catapult', 'Catapult'), ('innovate_uk', 'Innovate UK')], db_index=True, max_length=50)),
                ('grant_title', models.CharField(max_length=500)),
                ('before_snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('after_snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('field_changes', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrape_findings', to='grants.grant')),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='grants.scraperun')),
            ],
            options={
                'db_table': 'scrape_findings',
                'ordering': ['-created_at', 'finding_type', 'grant_title'],
                'indexes': [models.Index(fields=['scrape_run', 'finding_type'], name='scrape_find_scrape__dd945f_idx'), models.Index(fields=['grant_source', 'finding_type'], name='scrape_find_grant_s_a18c7d_idx'), models.Index(fields=['created_at'], name='scrape_find_created_710657_idx')],
            },
        ),
    ]
