# Generated by Django 5.0.1 on 2025-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('sic_codes', models.TextField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('date_of_creation', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_grants',
            },
        ),
        migrations.CreateModel(
            name='FundingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trl_level', models.CharField(blank=True, choices=[('TRL 1 - Basic principles observed', 'TRL 1 - Basic principles observed'), ('TRL 2 - Technology concept formulated', 'TRL 2 - Technology concept formulated'), ('TRL 3 - Experimental proof of concept', 'TRL 3 - Experimental proof of concept'), ('TRL 4 - Technology validated in lab', 'TRL 4 - Technology validated in lab'), ('TRL 5 - Technology validated in relevant environment', 'TRL 5 - Technology validated in relevant environment'), ('TRL 6 - Technology demonstrated in relevant environment', 'TRL 6 - Technology demonstrated in relevant environment'), ('TRL 7 - System prototype demonstration in operational environment', 'TRL 7 - System prototype demonstration in operational environment'), ('TRL 8 - System complete and qualified', 'TRL 8 - System complete and qualified'), ('TRL 9 - Actual system proven in operational environment', 'TRL 9 - Actual system proven in operational environment')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funding_searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantMatchWorkpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grant_match_workpackages',
            },
        ),
    ]
