# Generated by Django 5.0.1 on 2025-12-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companygrant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_grants', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companygrant',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_grants', to='grants.grant'),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_searches', to='companies.company'),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grantmatchworkpackage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_match_workpackages', to='companies.company'),
        ),
        migrations.AddField(
            model_name='grantmatchworkpackage',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_match_workpackages', to='grants.grant'),
        ),
        migrations.AddField(
            model_name='grantmatchworkpackage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_match_workpackages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_number'], name='companies_company_ea47c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companygrant',
            unique_together={('company', 'grant')},
        ),
        migrations.AddIndex(
            model_name='grantmatchworkpackage',
            index=models.Index(fields=['status'], name='grant_match_status_141412_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grantmatchworkpackage',
            unique_together={('company', 'grant')},
        ),
    ]
