# Generated by Django 5.0.1 on 2025-12-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(db_index=True)),
                ('match_reasons', models.JSONField(default=dict)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grant_match_results',
                'ordering': ['-match_score'],
            },
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='funding_searches/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='fundingsearch',
            index=models.Index(fields=['matching_status'], name='funding_sea_matchin_4090d1_idx'),
        ),
        migrations.AddField(
            model_name='grantmatchresult',
            name='funding_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='companies.fundingsearch'),
        ),
        migrations.AddField(
            model_name='grantmatchresult',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='grants.grant'),
        ),
        migrations.AddIndex(
            model_name='grantmatchresult',
            index=models.Index(fields=['funding_search', '-match_score'], name='grant_match_funding_7ee045_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grantmatchresult',
            unique_together={('funding_search', 'grant')},
        ),
    ]
