# Generated by Django 5.0.1 on 2025-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_grantmatchresult_fundingsearch_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='matching_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]

