# Generated by Django 5.0.1 on 2025-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_fundingsearch_matching_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='matching_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

