# Generated by Django 5.0.1 on 2025-12-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_fundingsearch_matching_progress'),
    ]

    operations = [
        # Make company_number nullable
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        # Add is_registered field
        migrations.AddField(
            model_name='company',
            name='is_registered',
            field=models.BooleanField(db_index=True, default=True),
        ),
        # Add registration_status field
        migrations.AddField(
            model_name='company',
            name='registration_status',
            field=models.CharField(
                choices=[('registered', 'Registered'), ('unregistered', 'Not Yet Registered')],
                db_index=True,
                default='registered',
                max_length=20
            ),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_registered'], name='companies_is_regi_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['registration_status'], name='companies_regist_789abc_idx'),
        ),
    ]

