# Generated by Django 5.0.1 on 2025-12-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_add_filing_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='companies_is_regi_4274b8_idx',
            old_name='companies_is_regi_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='companies_registr_9079ab_idx',
            old_name='companies_regist_789abc_idx',
        ),
    ]
