# Generated by Django 5.0.1 on 2025-12-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_trl_levels_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='selected_company_files',
            field=models.ManyToManyField(blank=True, related_name='funding_searches', to='companies.companyfile'),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='selected_company_notes',
            field=models.ManyToManyField(blank=True, related_name='funding_searches', to='companies.companynote'),
        ),
    ]
