# Generated by Django 5.0.1 on 2025-12-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_add_selected_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='use_company_website',
            field=models.BooleanField(default=False),
        ),
    ]
