# Generated by Django 5.0.1 on 2025-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_add_use_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmatchresult',
            name='competitiveness_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grantmatchresult',
            name='eligibility_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
