# Generated by Django 5.0.1 on 2025-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_add_score_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsearch',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=50),
        ),
    ]
