# Generated by Django 5.0.1 on 2025-12-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_add_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='selected_grant_sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
