# Generated by Django 5.0.1 on 2026-01-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_add_grant_source_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='let_system_decide_trl',
            field=models.BooleanField(default=False),
        ),
    ]
