# Generated by Django 5.0.1 on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_fundingsearchfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='exclude_closed_competitions',
            field=models.BooleanField(default=True),
        ),
    ]
