# Generated by Django 5.0.1 on 2026-01-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_add_funding_questionnaire'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fundingquestionnaire',
            new_name='funding_que_user_id_58e00d_idx',
            old_name='funding_que_user_id_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='fundingquestionnaire',
            new_name='funding_que_user_id_69bed1_idx',
            old_name='funding_que_user_id_is_def_idx',
        ),
        migrations.AddField(
            model_name='grantmatchresult',
            name='exclusions_score',
            field=models.FloatField(blank=True, db_index=True, help_text='0.0 to 1.0 - How well project avoids exclusions (higher = fewer exclusions apply)', null=True),
        ),
        migrations.AlterField(
            model_name='grantmatchresult',
            name='match_score',
            field=models.FloatField(db_index=True, help_text='0.0 to 1.0 - Overall score (average of eligibility, competitiveness, and exclusions scores)'),
        ),
    ]
