# Generated by Django migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_add_exclusions_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsearch',
            name='assess_exclusions',
            field=models.BooleanField(default=True, help_text='If True, assess exclusions checklist (recommended: assess first)'),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='assess_eligibility',
            field=models.BooleanField(default=True, help_text='If True, assess eligibility checklist (recommended: assess second)'),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='assess_competitiveness',
            field=models.BooleanField(default=True, help_text='If True, assess competitiveness checklist (recommended: assess last)'),
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='checklist_assessment_order',
            field=models.JSONField(blank=True, default=list, help_text='Order of checklist assessment: [\'exclusions\', \'eligibility\', \'competitiveness\']'),
        ),
    ]
