# Generated by Django 5.0.1 on 2026-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_add_preflight_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingsearch',
            name='selected_company_files',
        ),
        migrations.RemoveField(
            model_name='companynote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companynote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fundingsearch',
            name='selected_company_notes',
        ),
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='grantmatchresult',
            name='exclusions_score',
        ),
        migrations.AddField(
            model_name='fundingsearch',
            name='use_company_grant_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grantmatchresult',
            name='match_score',
            field=models.FloatField(db_index=True),
        ),
        migrations.DeleteModel(
            name='CompanyFile',
        ),
        migrations.DeleteModel(
            name='CompanyNote',
        ),
    ]
