# Generated by Django 5.0.1 on 2026-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_add_use_company_grant_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmatchresult',
            name='exclusions_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
