# Generated by Django 5.0.1 on 2026-01-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0002_slackbotlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slackbotlog',
            new_name='slack_bot_l_created_77c1ed_idx',
            old_name='slack_bot_l_created_idx',
        ),
        migrations.RenameIndex(
            model_name='slackbotlog',
            new_name='slack_bot_l_status_c6b520_idx',
            old_name='slack_bot_l_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='slackbotlog',
            new_name='slack_bot_l_message_8e77d2_idx',
            old_name='slack_bot_l_message_type_created_idx',
        ),
    ]
